QUESTIONS = 'sample_data/question.csv'
ANSWERS = 'sample_data/answer.csv'

ID_POSITION = 0
SUBMIOSION_TIME_POSITION = 1
VIEW_NUMBER_POSITION = 2
VOTE_NUMBER_POSITION = 3
TITLE_POSITION = 4
MESSAGE_POSITION = 5
IMAGE_POSITION = 6
